---
telegraf_influxdb_url: "http://10.0.0.81:8086"
telegraf_influxdb_database: "telegraf"
telegraf_influxdb_skip_database_creation: true
telegraf_influxdb_timeout: "10s"
telegraf_influxdb_username: "telegraf"
telegraf_influxdb_password: "telegraf"
