---
- name: Configure APT repository for InfluxDB and install Telegraf
  ansible.builtin.shell: |
    wget -q https://repos.influxdata.com/influxdata-archive_compat.key
    echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
    echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list

- name: Update APT packages
  ansible.builtin.apt:
    update_cache: true

- name: Install Telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present

# old
# - name: Install gnupg package
#   ansible.builtin.apt:
#     name: gnupg
#     state: present

# - name: Add InfluxData GPG key
#   ansible.builtin.apt_key:
#     url: https://repos.influxdata.com/influxdata-archive_compat.key
#     state: present

# - name: Add InfluxData repository
#   ansible.builtin.apt_repository:
#     repo: "deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main"
#     state: present

# - name: Update apt cache and install Telegraf
#   ansible.builtin.apt:
#     update_cache: yes
#     name: telegraf
#     state: present

